spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.1.132:3306/cursos?serverTimezone=UTC
    username: root
    password: root
  jpa:
    hibernate:
      naming.implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
      naming.physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostName: localhost
    instance-id: ${spring.application.name}:${random.value}
server:
  port: 8000 # 8000 8001 8002
